# Generated by Django 4.2.8 on 2024-05-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_contactus_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
