# Generated by Django 4.2.8 on 2024-04-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
