# Generated by Django 4.2.8 on 2024-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cartorder_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='pid',
            field=models.CharField(default='pid', max_length=20),
            preserve_default=False,
        ),
    ]
